import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider, SessionProvider } from '../providers'
import { Footer, Navbar } from '../components/common'
import { Toaster } from "sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Magic Touch",
  description: "Generated by create next app",
  icons: {
    icon: ['/logo.svg']
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased transition-all duraiton-300`}>
        <SessionProvider>
          <ThemeProvider attribute="class">
            <Navbar />
            {children}
            <Footer />
            <Toaster />
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
